title: "Coconut Codex"
url: "https://coconutswallow.github.io"
baseurl: "/codex"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Collections Configuration
collections:
  maps:
    output: true
  avrae_guide:
    output: true
    permalink: /avrae/:path/
  session_assets:
    output: true
    permalink: /session-assets/:path/
  other_assets:
    output: true
    permalink: /other-assets/:path/

# Navigation Menu Structure
navigation:
  - title: "Home"
    url: "/"
  - title: "House Rules"
    url: "/house-rules"
  - title: "Avrae Guide"
    url: "/avrae/"
  - title: "Battle Maps"
    url: "/maps"
  - title: "DM Links"
    url: "/dm-links"
  - title: "Session Assets"
    url: "/session-assets/"
  - title: "Other Assets"
    url: "/other-assets/"

# Default Layouts
defaults:
  - scope:
      path: ""
    values:
      layout: "default"